config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include("voting.urls")),
    path('user/', include("users.urls")),
    #path('__debug__/', include('debug_toolbar.urls')),

]

users/urls.py
from django.urls import path 

from .views import user_polls, close_poll, login, signup, logout

app_name = "users"

urlpatterns = [
    path("my_polls/", user_polls, name="user_polls"),
    path("close-poll/<str:secondary_id>/", close_poll, name="close_poll"),
    path("login/", login, name="login"),
    path("signup/", signup, name="signup"),
    path("logout/", logout, name="logout"),
    
]

voting/urls.py
from django.urls import path

from .views import index, add_question, add_option, vote


app_name = "voting"

urlpatterns = [
    path('', index, name="index"),
    path('add_question/', add_question, name="add_question"),
    path('add_option/', add_option, name="add_option"),
    path('vote/<str:question_secondary_id>/', vote, name="vote")
]

voting/models.py
import uuid 
from django.db import models
from django.contrib.auth.models import User


class Poll(models.Model):
    
    secondary_id = models.UUIDField(default=uuid.uuid4, editable=False)
    question = models.CharField(max_length=2000)
    created_by = models.ForeignKey(User, null=True, blank=True, related_name="polls", on_delete=models.SET_NULL)
    is_open = models.BooleanField(default=True)
    
    def __str__(self):
        return self.question
    
    @property 
    def total_voters(self):
        return self.votes.count()


class Option(models.Model):
    
    secondary_id = models.UUIDField(default=uuid.uuid4, editable=False)
    text = models.CharField(max_length=1000)
    poll = models.ForeignKey(Poll, null=False, blank=False, related_name="options", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.text
    
    @property 
    def vote_percentage(self):
        if not self.poll.total_voters == 0:
            return (self.votes.count() / self.poll.total_voters) * 100
        return 0
       
            
    
class AnonymousUser(models.Model):
    secondary_id = models.UUIDField(default=uuid.uuid4, editable=False)
    
    
    
class Vote(models.Model):
    
    poll = models.ForeignKey(Poll, null=False, blank=False, related_name="votes", on_delete=models.CASCADE)
    option = models.ForeignKey(Option, null=False, blank=False, related_name="votes", on_delete=models.CASCADE)
    voter = models.ForeignKey(AnonymousUser, null=False, blank=False, related_name="votes", on_delete=models.CASCADE)
    
    

voting/forms.py
from django import forms
from django.forms import modelformset_factory

from .models import Poll, Option


class QuestionForm(forms.ModelForm):
    
    class Meta:
        model = Poll
        fields = ['question']


class ChoiceForm(forms.Form):
    choice = forms.CharField(label='choice', max_length=1000)
    

OptionFormSet = modelformset_factory(
    Option, fields=("text", ), min_num=2, max_num=30,
)

voting/views.py
import json 
import time
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.core import serializers 
from django.views.decorators.http import require_http_methods 
from django.urls import reverse 

from .models import Poll, Option, AnonymousUser, Vote
from .forms import QuestionForm, OptionFormSet


def index(request):
    question_form = QuestionForm()
    option_formset = OptionFormSet(queryset=Option.objects.none())
    context = {
        'question_form': question_form,
        'option_formset': option_formset,
    }
    return render(request, 'voting/index.html', context)


@require_http_methods(["POST"])
def add_question(request):
    question_form = QuestionForm(request.POST)
    context = {}
    if question_form.is_valid():
        question = question_form.save(commit=False)
        if request.user.is_authenticated:
            question.created_by = request.user 
        question.save()
        request.session["current_question"] = question.id
        context["question_form"] = question_form
        context["question_status"] = "Question created"
        context["question_secondary_id"] = question.secondary_id
        return render(request, 'voting/partials/question-form.html', context)

    context["question_form"] = question_form
    return render(request, 'voting/partials/question-form.html', context)
    

@require_http_methods(["POST"])
def add_option(request):
    option_status = None
    question_id = request.session.get("current_question")
    if question_id is None:
        option_status = "Please add a question."
    if option_status is None:
        poll = Poll.objects.get(id=question_id)
        #data = json.loads(request.body).get('options')
        option_formset = OptionFormSet(data=request.POST)
        
        if option_formset.is_valid():
            instances = option_formset.save(commit=False)
            for instance in instances:
                instance.poll = poll
                instance.save()
            del request.session['current_question']
            response = HttpResponse()
            response.headers['HX-Redirect'] = reverse('voting:vote', kwargs={'question_secondary_id': poll.secondary_id})
            return response
            #return redirect(reverse('voting:vote', kwargs={'question_secondary_id': poll.secondary_id}))
            #return HttpResponse("It worked", status=201)
        return render(request, 'voting/partials/options-form.html',  {'option_formset': option_formset})
    return render(request, 'voting/partials/options-form.html',  {'option_status': option_status})
    #return HttpResponse(f"{error}", status=400)


def get_poll(secondary_id):
    try:
        poll = Poll.objects.prefetch_related('options', 'votes').get(secondary_id=secondary_id)
    except:
        poll = None 
    return poll 
    
    
def vote(request, question_secondary_id):
    # Query the poll and get the anonymous_user_id from session
    poll = get_poll(question_secondary_id)
    anonymous_user_id = request.session.get('anonymous_user_id')
    
    # Query AnonymousUser from DB and create, if it doesn’t exists already
    if anonymous_user_id is None:
        anonymous_user = AnonymousUser.objects.create()
        request.session['anonymous_user_id'] = anonymous_user.id 
    else:
        anonymous_user = AnonymousUser.objects.get(id=anonymous_user_id)
    
    #Get AnonymousUser Previous vote option if it exists or else set it to Null
    prev_vote = anonymous_user.votes.filter(poll=poll)
    context = {
        'poll': poll,
        'anonymous_user': anonymous_user,
        'prev_selected_option': prev_vote.first().option if prev_vote.exists() else None,
        'pollOptionsName': [option.text for option in poll.options.all()],
        'pollOptionsVoteParcentage':  [option.vote_percentage for option in poll.options.all()],
    }
    
    if request.method == "POST":
        if not poll.is_open:
            return HttpResponse("Poll is closed.")
        
        body = request.POST 
        
        if not poll.options.filter(secondary_id=body.get("option_secondary_id")).exists():
            return HttpResponse("Option doesn’t exist in poll options", status=400)
            
        vote = Vote.objects.filter(poll=poll, voter=anonymous_user)
        if vote.exists():
            if str(vote.first().option.secondary_id) == body.get("option_secondary_id"):
                context["vote_status"] = "Already voted."
                return render(request, 'voting/partials/vote-partial.html', context)
            vote.delete()
            
        selected_option = Option.objects.get(secondary_id=body.get("option_secondary_id"))
        new_vote = Vote.objects.create(poll=poll, option=selected_option, voter=anonymous_user)
        
        context['poll'] = get_poll(question_secondary_id)
        context['prev_selected_option'] = selected_option  
        context["vote_status"] = "Voted. Click to change vote."
        
        return render(request, 'voting/partials/vote-partial.html', context)
    return render(request, 'voting/vote.html', context)
    

def poll_raw_data(request:HttpRequest, question_secondary_id):
    poll = get_poll(question_secondary_id)
    

voting/templates/voting/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<main class="centered-element">
    
    <div id="cnsl"></div>
    
    <form method="post" id="question_form"
        hx-post="{% url 'voting:add_question' %}" hx-target="#question_form_partial" hx-swap="outerHTML"
        hx-select="#question_form_partial" hx-select-oob="#question_status" hx-swap-oob="true"
        >
        {% csrf_token %}
        <div id="question_form_partial">
        {{question_form.as_p}}
        </div>
        <div class="btn-center">
            <button type="submit">Create Question</button>
        </div>
    </form>
    <br />
    <div id="question_status"></div>
    <br />
    
    <form method="post" id="options_form"
        hx-post="{% url 'voting:add_option' %}" hx-target="#options_form_partial" hx-swap="outerHTML"
        hx-select="#options_form_partial" hx-select-oob="#option_status" hx-swap-oob="true"
        >
        {% csrf_token %}
        <div class="options_form_partial">
            {% include "voting/partials/options-form.html" %}
        </div>
        
        <button type="button" id="add_more_option_button">Add more option</button><br /><br />
        <div class="btn-center">
            <button type="submit">Create Options</button>
        </div>
    </form>
    <div id="option_status"></div>
    <br /> <br />
    
    <div class="btn-center">
        {% if user.is_authenticated %}
        <button>
            <a href="{% url 'users:user_polls' %}" class="link-no-color">My Polls</a>
        </button>
        {% else %}
        <button>
            <a href="{% url 'users:login' %}" class="link-no-color">Login</a>
        </button>
        <button>
            <a href="{% url 'users:signup' %}" class="link-no-color">Signup</a>
        </button>
        {% endif %}
    </div>
</main>
{% endblock content %}
{% block script %}
<script src="{% static 'js/voting/index.js' %}" defer></script>
{% endblock script %}

voting/templates/voting/vote.html
{% extends "base.html" %}
{% load static %}
{% load social_share %}
{% block title %}{{poll.question}} - {% endblock title %}
{% block content %}
<main class="centered-element">
    {% if poll %}
    <button id="click-to-copy" data-clipboard-text="{{ request.build_absolute_uri }}">Copy link</button>
    <span id="failed-to-copy"></span>
    <details>
        <summary>More share options</summary>
        <div class="ml dotted">
            {% post_to_facebook object_or_url "Facebook" %}
            {% post_to_twitter "{{poll.question}} - Anonymous vote" object_or_url "Twitter" %}
            {% post_to_reddit "{{poll.question}} - Anonymous vote" object_or_url "Reddit" %}
            {% post_to_whatsapp object_or_url "WhatsApp" %}
            {% post_to_telegram "Share via email" object_or_url "Telegram" %}
            {% send_email "{{poll.question}} - Anonymous vote" "{{poll.question}} - Anonymous vote" object_or_url "Email" %}
        </div>    
    </details> 
    <div class="custom-card poll">
        <h3 class="text-center question">{{poll.question}}</h3>
        <div id="vote_status">
            {% if poll.is_open %}
                {% if prev_selected_option %}
                Voted. Click to change vote.
                {% else %}
                Click to vote
                {% endif %}
            {% else %}
            Poll is closed. Here are the Results:
            {% endif %}
        </div>
        <div id="poll_details">
            {% include 'voting/partials/vote-partial.html' %}
        </div>
    </div>
    {% else %}
    <div>
        Poll not found.
    </div>
    {% endif %}

    {% if not poll.is_open %}
        <canvas id="dougnnutChart"></canvas>
    {% endif %}

</main>

{% endblock content %}
{% block script %}
<script src="{% static 'js/clipboard.js' %}"></script>
<script src="{% static 'js/voting/vote.js' %}"></script>

{% if not poll.is_open %}
{{ pollOptionsName|json_script:"pollOptionsName" }}
{{ pollOptionsVoteParcentage|json_script:"pollOptionsVoteParcentage" }}
<script src="{% static 'external-libraries/chart.js' %}"></script>
<script>
    const pollOptions = JSON.parse(document.getElementById('pollOptionsName').textContent);
    const pollOptionsVoteParcentage = JSON.parse(document.getElementById('pollOptionsVoteParcentage').textContent);
    
    const ctx = document.getElementById('dougnnutChart');

    const data = {
        labels: pollOptions,
        datasets: [{
            label: 'Vote parcentage',
            data: pollOptionsVoteParcentage,
            hoverOffset: 4
        }]
    };

    new Chart(ctx, {
    type: 'doughnut',
    data: data,
    options: {
        scales: {
        y: {
            beginAtZero: true
        }
        }
    }
    });
</script>
{% endif %}

{% endblock script %}