config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include("voting.urls")),
    path('user/', include("users.urls")),
    #path('__debug__/', include('debug_toolbar.urls')),

]

users/urls.py
from django.urls import path 

from .views import user_polls, close_poll, login, signup, logout

app_name = "users"

urlpatterns = [
    path("my_polls/", user_polls, name="user_polls"),
    path("close-poll/<str:secondary_id>/", close_poll, name="close_poll"),
    path("login/", login, name="login"),
    path("signup/", signup, name="signup"),
    path("logout/", logout, name="logout"),
    
]

voting/urls.py
from django.urls import path

from .views import index, add_question, add_option, vote


app_name = "voting"

urlpatterns = [
    path('', index, name="index"),
    path('add_question/', add_question, name="add_question"),
    path('add_option/', add_option, name="add_option"),
    path('vote/<str:question_secondary_id>/', vote, name="vote")
]

users/models.py
from django.db import models

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse 
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.urls import reverse 
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from voting.models import Poll


@login_required
def user_polls(request):
    polls = Poll.objects.filter(created_by=request.user)
    open_polls = Poll.objects.filter(created_by=request.user, is_open=True).count()
    closed_polls = Poll.objects.filter(created_by=request.user, is_open=False).count()
    
    context = {
        "polls": polls,
        "open_polls": open_polls,
        "closed_polls": closed_polls
    }
    return render(request, "users/user-polls.html", context=context)
    

@login_required
def close_poll(request, secondary_id):
    if request.method == "POST":
        try:
            poll = Poll.objects.prefetch_related('options', 'votes').get(secondary_id=secondary_id)
        except:
            response = "Poll doesn’t exist."
        if not request.user == poll.created_by:
            response = "Not allowed"
        else:
            poll.is_open = False
            poll.save()
            response = "Closed"
        return HttpResponse(response)
  
  
def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        
        if not username or not password:
            return HttpResponse("Username or Password can't be empty")

        user = authenticate(request, username=username, password=password)
        if user is None:
            response = "Username or Password is incorrect"
            return HttpResponse(response)
        else:
            auth_login(request, user)
            response = HttpResponse()
            response.headers['HX-Redirect'] = reverse('users:user_polls')
            return response
            
    return render(request, "users/login.html")
    

def signup(request):
    if not request.user.is_authenticated:
        
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            
            if form.is_valid():
                user = form.save()
                auth_login(request, user)
                messages.success(request, f"Signed up as {user.username}")
                response = HttpResponse()
                response.headers['HX-Redirect'] = reverse('users:user_polls')
                return response 
            print(form.as_p())
            return HttpResponse(form.as_p())
            
        form = UserCreationForm()
        return render(request, 'users/signup.html', {'form': form})
        
    return redirect(request.META.get('HTTP_REFERER', '/'))
    

def logout(request):
    auth_logout(request)
    messages.info(request, "Logged out")
    return redirect("/")

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<main class="centered-element">

    <form method="post" id="login_form"
        hx-post="{% url 'users:login' %}" hx-target="#login_status" hx-swap="innerHTML"
        >
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" />
        <label for="password">Password:</label>
        <input type="password" name="password" />
        <div id="login_status"></div>
        <div class="btn-center">
            <button type="submit">Login</button>
        </div>
    </form>
</main>
{% endblock content %}
{% block script %}
<script src="{% static 'js/voting/index.js' %}" defer></script>
{% endblock script %}

users/templates/users/signup.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<main class="centered-element">

    <form method="post" id="login_form"
        hx-post="{% url 'users:signup' %}" hx-target="#signupFormContainer" hx-swap="innerHTML"
        >
        {% csrf_token %}
        <div id="signupFormContainer">
        {{ form.as_p }}
        </div>
        <div id="login_status"></div>
        <div class="btn-center">
            <button type="submit">Sign UP</button>
        </div>
    </form>
</main>
{% endblock content %}
{% block script %}
<script src="{% static 'js/voting/index.js' %}" defer></script>
{% endblock script %}

users/templates/users/user-polls.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<main class="centered-element">
    Total polls created: {{polls.count}}<br />
    Open polls: {{open_polls}}<br />
    Closed polls: {{closed_polls}}<br /><br />
    <div class="btn-center">
        <button>
            <a href="{% url 'voting:index' %}" class="link-no-color">Create new poll</a>
        </button>
        <button>
            <a href="{% url 'users:logout' %}" class="link-no-color">Log out</a>
        </button>
    </div>
    <br />
    <table>
        <tr>
            <th>Poll name</th>
            <th>Total votes</th>
            <th>Status/Action</th>
        </tr>
        {% for poll in polls %}
        <tr>
            <td class="text-center">
                <a href="{% url 'voting:vote' poll.secondary_id %}">{{poll.question}}</a>
            </td>
            <td class="text-center">
                {{poll.total_voters}}
            </td>
            <td class="text-center" id="close-poll-status">
                {% if poll.is_open %}
                <button onclick="closePoll(this, `{% url 'users:close_poll' poll.secondary_id %}`)">Close poll</button>
                {% else %}
                Closed
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</main>
{% endblock content %}
{% block script %}
<script src="{% static 'js/users/userpolls.js' %}"></script>
{% endblock script %}